version: "3.4"
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/24

services:
  mysql:
    build: config/mysql
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - ./mysql-db:/var/lib/mysql
    - ./logs/mysql/:/var/log/mysql
    ports:
    - "3306"
    networks:
      - internal

  webserver:
    build: config/nginx
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    working_dir: /application
    volumes:
    - ./app:/application
    - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./logs/nginx:/var/log/nginx
    depends_on:
      - "mysql"
      - "php-fpm"
    ports:
    - "${NGINX_EXTERNAL_PORT}:80"
    networks:
      - internal  

  php-fpm:
    build: config/php-fpm/${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    working_dir: /application
    volumes:
    - ./app:/application
    - ./config/php-fpm/${PHP_VERSION}/php-fpm.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-overrides.ini
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  redis:
    image: "redis:alpine"
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    networks:
      - internal
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"

  composer:
    restart: 'no'
    image: composer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_composer
    working_dir: /application
    command: bash -c "composer install --ignore-platform-reqs --no-scripts && composer du"
    volumes:
      - ./app:/application
