version: "3.4"
networks:
  network-name:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.195.128.0/24

services:
  mariadb:
    image: mariadb:10.1
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - ./mysql-db:/var/lib/mysql
    ports:
    - "3306"
    networks:
      network-name:
        ipv4_address: 10.195.128.2

  webserver:
    image: nginx:stable
    working_dir: /application
    volumes:
    - ./app:/application
    - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "mariadb"
      - "php-fpm"
    ports:
    - "8001:80"
    networks:
      network-name:
        ipv4_address: 10.195.128.3

  php-fpm:
    build: config/php-fpm/${PHP_VERSION}
    working_dir: /application
    volumes:
    - ./app:/application
    - ./config/php-fpm/${PHP_VERSION}/php-fpm.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-overrides.ini
    networks:
      network-name:
        ipv4_address: 10.195.128.4

  composer:
    restart: 'no'
    image: composer:latest
    working_dir: /application
    command: composer install --ignore-platform-reqs --no-scripts
    volumes:
    - ./app:/application
