version: "3.4"
services:
  mariadb:
    restart: 'always'
    image: mariadb:10.1
    volumes:
    - ./mysql-dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
    - "3306"